version: '3'
services:
  db:
    image: mongo
    command: mongod 
    ports:
      - "27017:27017"
    volumes:
      - /data/db:/tmp
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/jinda
    ports:
      - "3000:3000"
    depends_on:
      - db
